### ISSUE TITLE
Remove private construct from environment class

### ISSUE THREAD

**Issue by prisis** [jpcercal/environment#3]
No need for this.

**Comment by jpcercal** [comment]
Hello @prisis, this statement is required to the developers do not perform it:

$env = new Environment();

That does not make sense because the environment class is used only to get the environment variables that are already registered. But, i agree with you, and i will improvement this statement to throw a Exception when execute the constructor method. What do you do think?

**Comment by prisis** [comment]
Hey @jpcercal, sorry i did forget about this haha...

The best solutions is to remove it.
All php developer know how to use a static class.

Or you make a new class for static and normal use, like https://github.com/danielstjules/Stringy/tree/master/src

**Comment by jpcercal** [comment]
I know that all php developers knows how to use a static class this is not a question is a fact. But, i really can not see a reason to remove this statement. 

Your suggestion to create a new Static class is interesting. 

Then, i implemented this features in the commit 3f22994

Thanks guy!

**Comment by prisis** [comment]
I like it :)
